"""Add analytics fields to Position

Revision ID: 3d2230ce1564
Revises: 5675b611be2c
Create Date: 2026-08-02 23:58:04.425036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2230ce1564'
down_revision: Union[str, Sequence[str], None] = '5675b611be2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('liquidity', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('volume_24h', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('age_minutes', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('dex', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('buys', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('sells', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('is_win', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'is_win')
    op.drop_column('positions', 'sells')
    op.drop_column('positions', 'buys')
    op.drop_column('positions', 'dex')
    op.drop_column('positions', 'age_minutes')
    op.drop_column('positions', 'volume_24h')
    op.drop_column('positions', 'liquidity')
    op.drop_column('positions', 'market_cap')
    # ### end Alembic commands ###
