"""Add max_open_positions to Wallet

Revision ID: 5675b611be2c
Revises: d81dd415cc4e
Create Date: 2026-08-02 18:15:07.961819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5675b611be2c'
down_revision: Union[str, Sequence[str], None] = 'd81dd415cc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('max_open_positions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'max_open_positions')
    # ### end Alembic commands ###
