"""Add signal tracking and snapshots

Revision ID: 8f653720e3dc
Revises: 3d2230ce1564
Create Date: 2026-08-03 00:13:03.758340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f653720e3dc'
down_revision: Union[str, Sequence[str], None] = '3d2230ce1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_wallet_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('realized_profit', sa.Float(), nullable=False),
    sa.Column('unrealized_profit', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_wallet_snapshots_date'), 'daily_wallet_snapshots', ['date'], unique=True)
    op.create_index(op.f('ix_daily_wallet_snapshots_id'), 'daily_wallet_snapshots', ['id'], unique=False)
    op.add_column('signals', sa.Column('price_usd', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('peak_price_1h', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('peak_price_6h', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('peak_price_24h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'peak_price_24h')
    op.drop_column('signals', 'peak_price_6h')
    op.drop_column('signals', 'peak_price_1h')
    op.drop_column('signals', 'price_usd')
    op.drop_index(op.f('ix_daily_wallet_snapshots_id'), table_name='daily_wallet_snapshots')
    op.drop_index(op.f('ix_daily_wallet_snapshots_date'), table_name='daily_wallet_snapshots')
    op.drop_table('daily_wallet_snapshots')
    # ### end Alembic commands ###
