"""add_live_data_collection

Revision ID: f092dd9b0bea
Revises: 8f653720e3dc
Create Date: 2026-08-03 06:52:51.902180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f092dd9b0bea'
down_revision: Union[str, Sequence[str], None] = '8f653720e3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('buys', sa.Integer(), nullable=True),
    sa.Column('sells', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_snapshots_id'), 'token_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_token_snapshots_timestamp'), 'token_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_snapshots_token_address'), 'token_snapshots', ['token_address'], unique=False)
    op.add_column('positions', sa.Column('highest_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('lowest_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('max_roi', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('min_roi', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('hit_10_pct', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('hit_20_pct', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('hit_50_pct', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('hit_100_pct', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('did_rug', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('time_to_10_pct', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('time_to_20_pct', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('time_to_50_pct', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('time_to_100_pct', sa.Float(), nullable=True))
    op.add_column('tokens', sa.Column('price_usd', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('fdv', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('volume_5m', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('volume_1h', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('buys_5m', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('buys_1h', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('buys_24h', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('sells_5m', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('sells_1h', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('sells_24h', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('price_change_5m', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('price_change_1h', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('price_change_6h', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('price_change_24h', sa.Float(), nullable=False))
    op.add_column('tokens', sa.Column('age_minutes', sa.Float(), nullable=True))
    op.add_column('tokens', sa.Column('dex', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('chain', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('pair_address', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('website', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('telegram', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('image', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'updated_at')
    op.drop_column('tokens', 'description')
    op.drop_column('tokens', 'image')
    op.drop_column('tokens', 'telegram')
    op.drop_column('tokens', 'twitter')
    op.drop_column('tokens', 'website')
    op.drop_column('tokens', 'pair_address')
    op.drop_column('tokens', 'chain')
    op.drop_column('tokens', 'dex')
    op.drop_column('tokens', 'age_minutes')
    op.drop_column('tokens', 'price_change_24h')
    op.drop_column('tokens', 'price_change_6h')
    op.drop_column('tokens', 'price_change_1h')
    op.drop_column('tokens', 'price_change_5m')
    op.drop_column('tokens', 'sells_24h')
    op.drop_column('tokens', 'sells_1h')
    op.drop_column('tokens', 'sells_5m')
    op.drop_column('tokens', 'buys_24h')
    op.drop_column('tokens', 'buys_1h')
    op.drop_column('tokens', 'buys_5m')
    op.drop_column('tokens', 'volume_1h')
    op.drop_column('tokens', 'volume_5m')
    op.drop_column('tokens', 'fdv')
    op.drop_column('tokens', 'price_usd')
    op.drop_column('signals', 'time_to_100_pct')
    op.drop_column('signals', 'time_to_50_pct')
    op.drop_column('signals', 'time_to_20_pct')
    op.drop_column('signals', 'time_to_10_pct')
    op.drop_column('signals', 'did_rug')
    op.drop_column('signals', 'hit_100_pct')
    op.drop_column('signals', 'hit_50_pct')
    op.drop_column('signals', 'hit_20_pct')
    op.drop_column('signals', 'hit_10_pct')
    op.drop_column('positions', 'min_roi')
    op.drop_column('positions', 'max_roi')
    op.drop_column('positions', 'lowest_price')
    op.drop_column('positions', 'highest_price')
    op.drop_index(op.f('ix_token_snapshots_token_address'), table_name='token_snapshots')
    op.drop_index(op.f('ix_token_snapshots_timestamp'), table_name='token_snapshots')
    op.drop_index(op.f('ix_token_snapshots_id'), table_name='token_snapshots')
    op.drop_table('token_snapshots')
    # ### end Alembic commands ###
